### ISSUE TITLE
[BUG] shop branch - Unable to open GUI

### ISSUE THREAD

**Issue by Akik4** [architects-land/bedwars#13]
Issue while trying open GUI shop after right clicked a villager 
![image](https://github.com/architects-land/bedwars/assets/51128959/c3f0a2c3-ea9c-474e-9cc7-552d5f507670)

**Comment by anhgelus** [comment]
Was it fixed by f9c4585c28acf9969aeec8b4262406b7ad36c8d3 ?

**Comment by Akik4** [comment]
Yes that was fixed

**Comment by anhgelus** [comment]
Perfect
